<?php
/**
 * Created by IntelliJ IDEA.
 * User: wuzesheng
 * Date: 3/24/14
 * Time: 3:38 PM
 */

namespace FDS;

use Exception;

class GalaxyFDSClientException extends \Exception {

  public function __construct($message = "",
                              $code = 0,
                              Exception $previous = null) {
    parent::__construct($message, $code, $previous);
    // TODO(wuzesheng): Change the autogenerated stub
  }
}